# Refactoring of all postprocessing

In [1]:
# Dynamic reloading of src code
%load_ext autoreload
%autoreload 2

In [2]:
import os
import pandas as pd
from src.processing.utils import load_data
from src.processing.process_all_stats import make_team_indicators, make_player_indicators

## Load Raw Data

In [3]:
%%time
df = load_data()
# df = df[:10_000]
print(df.shape)

(127652, 62)
CPU times: user 1.61 s, sys: 326 ms, total: 1.94 s
Wall time: 1.97 s

## Team statistics by game

In [4]:
%%time
df_1 = make_team_indicators(df)

CPU times: user 14.7 s, sys: 892 ms, total: 15.6 s
Wall time: 15.7 s

In [5]:
df_1.columns

Index(['year', 'team', 'opponent', 'date', 'game', 'Assists', 'Hockey Assists',
       'Throwaways', 'Turnovers', 'Completions', 'Catches', 'Goals', 'Drops',
       'Blocks', 'Stalls', 'Callahans', 'Callahans Thrown', 'O Points Played',
       'O Possessions Played', 'D Points Played', 'D Possessions Played',
       'Holds', 'Breaks', 'Games Played',
       'Opponent Possessions Played (O-Line)',
       'Opponent Possessions Played (D-Line)', 'O Points Lost',
       'D Points Lost', 'Points Won', 'Points Played', 'Possessions Played',
       'Hold Rate', 'Break Rate', 'Scoring Efficiency',
       'O-line Scoring Efficiency', 'D-line Scoring Efficiency',
       'O-line Takeaway Efficiency', 'D-line Takeaway Efficiency'],
      dtype='object')

In [6]:
df_1.head()

,year,team,opponent,date,game,Assists,Hockey Assists,Throwaways,Turnovers,Completions,...,Points Won,Points Played,Possessions Played,Hold Rate,Break Rate,Scoring Efficiency,O-line Scoring Efficiency,D-line Scoring Efficiency,O-line Takeaway Efficiency,D-line Takeaway Efficiency
0,2018,Atlanta Hustle,Austin Sol,2018-05-05,Atlanta Hustle_Austin Sol_2018-05-05,22,20,11,12,234,...,22,48,36,0.640000,0.260870,0.611111,0.551724,0.857143,0.363636,0.347826
1,2018,Atlanta Hustle,Austin Sol,2018-05-19,Atlanta Hustle_Austin Sol_2018-05-19,19,19,21,28,253,...,19,51,47,0.533333,0.142857,0.404255,0.421053,0.333333,0.454545,0.407407
2,2018,Atlanta Hustle,Dallas Roughnecks,2018-05-20,Atlanta Hustle_Dallas Roughnecks_2018-05-20,20,18,20,24,196,...,20,51,46,0.607143,0.130435,0.434783,0.447368,0.375000,0.611111,0.321429
3,2018,Atlanta Hustle,Dallas Roughnecks,2018-06-03,Atlanta Hustle_Dallas Roughnecks_2018-06-03,28,24,11,15,227,...,28,58,43,0.724138,0.241379,0.651163,0.636364,0.700000,0.333333,0.363636
4,2018,Atlanta Hustle,Dallas Roughnecks,2018-06-16,Atlanta Hustle_Dallas Roughnecks_2018-06-16,20,18,17,19,205,...,20,47,40,0.720000,0.090909,0.500000,0.545455,0.285714,0.615385,0.296296

In [7]:
df_1.describe()

,year,Assists,Hockey Assists,Throwaways,Turnovers,Completions,Catches,Goals,Drops,Blocks,...,Points Won,Points Played,Possessions Played,Hold Rate,Break Rate,Scoring Efficiency,O-line Scoring Efficiency,D-line Scoring Efficiency,O-line Takeaway Efficiency,D-line Takeaway Efficiency
count,341.0,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,...,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000
mean,2018.0,22.809384,21.049853,19.609971,23.800587,261.307918,261.307918,22.873900,3.868035,12.316716,...,22.809384,48.800587,47.398827,0.678014,0.257211,0.488091,0.516313,0.434775,0.562618,0.485409
std,0.0,5.324364,5.135846,6.643689,7.900194,52.963047,52.963047,5.341727,2.466876,4.819017,...,5.324364,7.840776,7.424475,0.129482,0.124486,0.112679,0.123075,0.180451,0.183211,0.124181
min,2018.0,6.000000,5.000000,2.000000,4.000000,64.000000,64.000000,6.000000,0.000000,0.000000,...,6.000000,13.000000,12.000000,0.205128,0.000000,0.153846,0.163265,0.000000,0.000000,0.181818
25%,2018.0,19.000000,18.000000,15.000000,19.000000,227.000000,227.000000,19.000000,2.000000,9.000000,...,19.000000,44.000000,43.000000,0.593750,0.166667,0.409091,0.428571,0.315789,0.444444,0.400000
50%,2018.0,23.000000,21.000000,18.000000,23.000000,262.000000,262.000000,23.000000,4.000000,12.000000,...,23.000000,49.000000,47.000000,0.689655,0.258065,0.490196,0.518519,0.437500,0.562500,0.481481
75%,2018.0,26.000000,25.000000,24.000000,28.000000,291.000000,291.000000,26.000000,5.000000,15.000000,...,26.000000,54.000000,52.000000,0.769231,0.333333,0.568182,0.600000,0.555556,0.684211,0.571429
max,2018.0,39.000000,35.000000,40.000000,58.000000,445.000000,445.000000,40.000000,16.000000,30.000000,...,39.000000,71.000000,72.000000,1.000000,0.750000,0.760870,0.826087,1.000000,1.000000,0.836735

## Team statistics by year

In [8]:
%%time
df_2 = make_team_indicators(df, index_vars=['year', 'team'])

CPU times: user 3.19 s, sys: 728 ms, total: 3.92 s
Wall time: 3.94 s

In [9]:
df_2.head()

,year,team,Assists,Hockey Assists,Throwaways,Turnovers,Completions,Catches,Goals,Drops,...,Points Won,Points Played,Possessions Played,Hold Rate,Break Rate,Scoring Efficiency,O-line Scoring Efficiency,D-line Scoring Efficiency,O-line Takeaway Efficiency,D-line Takeaway Efficiency
0,2018,Atlanta Hustle,315,295,186,237,3412,3412,316,44,...,315,675,566,0.685629,0.252199,0.556537,0.549161,0.577181,0.514286,0.421446
1,2018,Austin Sol,316,279,307,359,3408,3408,320,49,...,316,712,683,0.617886,0.256560,0.462665,0.475992,0.431373,0.517544,0.473333
2,2018,Chicago Wildfire,319,298,235,299,3786,3786,319,62,...,319,674,626,0.692073,0.265896,0.509585,0.527907,0.469388,0.597826,0.469526
3,2018,DC Breeze,342,319,292,351,4146,4146,343,55,...,342,715,705,0.671470,0.296196,0.485106,0.491561,0.471861,0.596491,0.517672
4,2018,Dallas Roughnecks,408,369,363,428,4824,4824,410,56,...,408,825,853,0.739691,0.276888,0.478312,0.544592,0.371166,0.657778,0.563492

## Player statistics by game

In [10]:
%%time
df_3 = make_player_indicators(df)

CPU times: user 1min 10s, sys: 1.53 s, total: 1min 11s
Wall time: 1min 12s

In [11]:
df_3.head()

,year,team,player,Assists,Hockey Assists,Throwaways,Turnovers,Completions,Catches,Goals,...,Points Won,Points Played,Possessions Played,Hold Rate,Break Rate,Scoring Efficiency,O-line Scoring Efficiency,D-line Scoring Efficiency,O-line Takeaway Efficiency,D-line Takeaway Efficiency
0,2018,Atlanta Hustle,Adam Burgess,0.0,1.0,1.0,1.0,6.0,8.0,0.0,...,6.0,18.0,13.0,0.666667,0.000000,0.461538,0.600000,0.000000,0.500000,0.250000
1,2018,Atlanta Hustle,Allan Laviolette,7.0,8.0,4.0,4.0,51.0,49.0,4.0,...,33.0,76.0,53.0,0.696970,0.232558,0.622642,0.621622,0.625000,0.416667,0.367347
2,2018,Atlanta Hustle,Anders Olsen,2.0,1.0,4.0,5.0,32.0,44.0,10.0,...,23.0,54.0,51.0,0.500000,0.333333,0.450980,0.394737,0.615385,0.409091,0.448276
3,2018,Atlanta Hustle,Andrell Caldwell,0.0,0.0,2.0,3.0,10.0,10.0,0.0,...,3.0,8.0,9.0,0.666667,0.200000,0.333333,0.400000,0.250000,0.666667,0.571429
4,2018,Atlanta Hustle,Anonymous,0.0,0.0,0.0,0.0,5.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN