In [2]:
import ultianalyticspull as uap

# Investigate the Pro Leagues

## Premier Ultimate League - PUL

In [2]:
pul_pull = uap.LeaguePuller(league = 'pul')

2019 Atlanta Soul
2019 Austin Torch
2019 Columbus Pride
2019 Indy Red
2019 Medellin Revolution
2019 Nashville Nightshade
2019 New York Gridlock
2019 Raleigh Radiance

In [3]:
pul_df = uap.load_league_data('pul')
pul_df.shape

(13815, 63)

In [4]:
pul_df.team.value_counts()

Raleigh Radiance        2300
Atlanta Soul            2005
Medellin Revolution     1832
New York Gridlock       1764
Columbus Pride          1502
Nashville Nightshade    1490
Austin Torch            1484
Indy Red                1438
Name: team, dtype: int64

In [5]:
pul_teams = uap.make_team_indicators(pul_df)
pul_teams

,year,team,Assists,Hockey Assists,Throws,Throwaways,Turnovers,Completions,Catches,Goals,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2019,Atlanta Soul,124,116,1443,138,160,1283,1283,124,...,0.095634,0.085932,0.096648,0.635036,0.272059,0.435088,0.432836,0.440476,0.619048,0.486188
1,2019,Austin Torch,84,78,1046,134,171,876,876,84,...,0.128107,0.080306,0.095890,0.743590,0.288889,0.329412,0.402778,0.234234,0.817073,0.680473
2,2019,Columbus Pride,78,73,1074,140,169,905,905,78,...,0.130354,0.072626,0.086188,0.517647,0.404762,0.314516,0.285714,0.361702,0.672897,0.690141
3,2019,Indy Red,55,42,1054,157,201,854,854,55,...,0.148956,0.052182,0.064403,0.465909,0.225806,0.214008,0.248485,0.152174,0.697479,0.678571
4,2019,Medellin Revolution,105,95,1381,93,126,1255,1255,105,...,0.067343,0.076032,0.083665,0.784810,0.401869,0.452586,0.508197,0.390909,0.758621,0.660819
5,2019,Nashville Nightshade,72,68,1071,143,177,894,894,72,...,0.133520,0.067227,0.080537,0.563636,0.125000,0.289157,0.340659,0.149254,0.640351,0.525547
6,2019,New York Gridlock,94,87,1296,126,164,1132,1132,95,...,0.097222,0.072531,0.083922,0.635417,0.317308,0.364341,0.374233,0.347368,0.711340,0.633540
7,2019,Raleigh Radiance,117,110,1714,180,212,1502,1502,117,...,0.105018,0.068261,0.077896,0.657895,0.336000,0.353474,0.384615,0.308824,0.743119,0.647887

In [8]:
pul_games = uap.make_team_indicators(pul_df, by_game=True)
pul_games.head()

,year,team,opponent,date,game,Assists,Hockey Assists,Throws,Throwaways,Turnovers,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2019,Atlanta Soul,Austin Torch,2019-05-01,Atlanta Soul_Austin Torch_2019-05-01,19,18,271,20,27,...,0.073801,0.070111,0.077869,0.687500,0.380952,0.404255,0.379310,0.444444,0.812500,0.612903
1,2019,Atlanta Soul,Medellin Revolution,2019-04-20,Atlanta Soul_Medellin Revolution_2019-04-20,20,18,232,26,30,...,0.112069,0.086207,0.099010,0.531250,0.142857,0.400000,0.395349,0.428571,0.440000,0.333333
2,2019,Atlanta Soul,Medellin Revolution,2019-05-07,Atlanta Soul_Medellin Revolution_2019-05-07,17,16,206,25,29,...,0.121359,0.082524,0.096045,0.695652,0.052632,0.369565,0.444444,0.100000,0.684211,0.357143
3,2019,Atlanta Soul,Medellin Revolution,2019-06-28,Atlanta Soul_Medellin Revolution_2019-06-28,26,26,288,21,24,...,0.072917,0.090278,0.098485,0.571429,0.344828,0.520000,0.484848,0.588235,0.400000,0.485714
4,2019,Atlanta Soul,Nashville Nightshade,2019-06-02,Atlanta Soul_Nashville Nightshade_2019-06-02,23,20,201,26,28,...,0.129353,0.114428,0.132948,0.823529,0.360000,0.450980,0.466667,0.428571,0.928571,0.594595

In [9]:
pul_players = uap.make_player_indicators(pul_df)
pul_players.head()

,year,team,player,Assists,Hockey Assists,Throws,Throwaways,Turnovers,Completions,Catches,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2019,Atlanta Soul,A Smith,1.0,2.0,4.0,0.0,0.0,4.0,4.0,...,0.000000,0.250000,0.000000,0.714286,0.133333,0.538462,0.500000,0.666667,0.600000,0.250000
1,2019,Atlanta Soul,Angela Lin,0.0,0.0,8.0,2.0,2.0,6.0,7.0,...,0.250000,0.000000,0.000000,0.500000,0.250000,0.444444,0.333333,0.500000,0.500000,0.466667
2,2019,Atlanta Soul,Anonymous,0.0,0.0,2.0,0.0,0.0,2.0,0.0,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,Atlanta Soul,Anraya Palmer,0.0,3.0,22.0,5.0,6.0,17.0,11.0,...,0.227273,0.000000,0.000000,0.833333,0.217391,0.409836,0.465116,0.277778,0.863636,0.500000
4,2019,Atlanta Soul,Caroline Taylor,1.0,5.0,49.0,2.0,3.0,46.0,52.0,...,0.040816,0.020408,0.076923,0.571429,0.437500,0.391753,0.369231,0.437500,0.657143,0.673469

## American Ultimate Disc League - AUDL

In [2]:
audl_pull = uap.LeaguePuller(league = 'audl',output_dir='./')

2014 Chicago Wildfire
2014 Cincinnati Revolution
2014 DC Breeze
2014 Detroit Mechanix
2014 Indianapolis AlleyCats
2014 Madison Radicals
2014 Minnesota Wind Chill
2014 Montreal Royal
2014 New York Empire
2014 Philadelphia Phoenix
2014 Rochester Dragons
2014 Salt Lake Lions
2014 San Francisco FlameThrowers
2014 San Jose Spiders
2014 Seattle Raptors
2014 Toronto Rush
2014 Vancouver Riptide
2015 Atlanta Hustle
2015 Charlotte Express
2015 Chicago Wildfire
2015 Cincinnati Revolution
2015 DC Breeze
2015 Detroit Mechanix
2015 Indianapolis AlleyCats
2015 Jacksonville Cannons
2015 Los Angeles Aviators
2015 Madison Radicals
2015 Minnesota Wind Chill
2015 Montreal Royal
2015 Nashville NightWatch
2015 New York Empire
2015 Ottawa Outlaws
2015 Philadelphia Phoenix
2015 Pittsburgh Thunderbirds
2015 Raleigh Flyers
2015 Rochester Dragons
2015 San Diego Growlers
2015 San Francisco FlameThrowers
2015 San Jose Spiders
2015 Seattle Cascades
2015 Toronto Rush
2015 Vancouver Riptide
2016 Atlanta Hustle
2016 Austin Sol
2016 Charlotte Express
2016 Chicago Wildfire
2016 Cincinnati Revolution
2016 DC Breeze
2016 Dallas Roughnecks
2016 Detroit Mechanix
2016 Indianapolis AlleyCats
2016 Jacksonville Cannons
2016 Los Angeles Aviators
2016 Madison Radicals
2016 Minnesota Wind Chill
2016 Montreal Royal
2016 Nashville NightWatch
2016 New York Empire
2016 Ottawa Outlaws
2016 Philadelphia Phoenix
2016 Pittsburgh Thunderbirds
2016 Raleigh Flyers
2016 San Diego Growlers
2016 San Francisco FlameThrowers
2016 San Jose Spiders
2016 Seattle Cascades
2016 Toronto Rush
2016 Vancouver Riptide
2017 Atlanta Hustle
2017 Austin Sol
2017 Chicago Wildfire
2017 DC Breeze
2017 Dallas Roughnecks
2017 Detroit Mechanix
2017 Indianapolis AlleyCats
2017 Jacksonville Cannons
2017 Los Angeles Aviators
2017 Madison Radicals
2017 Minnesota Wind Chill
2017 Montreal Royal
2017 Nashville NightWatch
2017 New York Empire
2017 Ottawa Outlaws
2017 Philadelphia Phoenix
2017 Pittsburgh Thunderbirds
2017 Raleigh Flyers
2017 San Diego Growlers
2017 San Francisco FlameThrowers
2017 San Jose Spiders
2017 Seattle Cascades
2017 Toronto Rush
2017 Vancouver Riptide
2018 Atlanta Hustle
2018 Austin Sol
2018 Chicago Wildfire
2018 DC Breeze
2018 Dallas Roughnecks
2018 Detroit Mechanix
2018 Indianapolis AlleyCats
2018 Los Angeles Aviators
2018 Madison Radicals
2018 Minnesota Wind Chill
2018 Montreal Royal
2018 Nashville NightWatch
2018 New York Empire
2018 Ottawa Outlaws
2018 Philadelphia Phoenix
2018 Pittsburgh Thunderbirds
2018 Raleigh Flyers
2018 San Diego Growlers
2018 San Francisco FlameThrowers
2018 San Jose Spiders
2018 Seattle Cascades
2018 Tampa Bay Cannons
2018 Toronto Rush
2019 Atlanta Hustle
2019 Austin Sol
2019 Chicago Wildfire
2019 DC Breeze
2019 Dallas Roughnecks
2019 Detroit Mechanix
2019 Indianapolis AlleyCats
2019 Los Angeles Aviators
2019 Madison Radicals
2019 Minnesota Wind Chill
2019 Montreal Royal
2019 New York Empire
2019 Ottawa Outlaws
2019 Philadelphia Phoenix
2019 Pittsburgh Thunderbirds
2019 Raleigh Flyers
2019 San Diego Growlers
2019 San Jose Spiders
2019 Seattle Cascades
2019 Tampa Bay Cannons
2019 Toronto Rush

In [10]:
audl_df = uap.load_league_data('audl')

In [11]:
audl_teams = uap.make_team_indicators(audl_df)
audl_teams

,year,team,Assists,Hockey Assists,Throws,Throwaways,Turnovers,Completions,Catches,Goals,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2014,Chicago Wildfire,324,285,3757,291,365,3392,3392,324,...,0.077455,0.086239,0.095519,0.702422,0.350725,0.466187,0.503722,0.414384,0.627660,0.617647
1,2014,Cincinnati Revolution,257,206,3014,330,416,2598,2598,258,...,0.109489,0.085269,0.099307,0.537815,0.228070,0.378498,0.381710,0.369318,0.531690,0.488372
2,2014,DC Breeze,346,302,3842,297,370,3482,3482,347,...,0.077303,0.090057,0.099655,0.612637,0.334239,0.476584,0.453252,0.525641,0.517787,0.530655
3,2014,Detroit Mechanix,217,176,3504,405,518,2988,2988,217,...,0.115582,0.061929,0.072624,0.454315,0.156379,0.292453,0.304940,0.245161,0.515075,0.477654
4,2014,Indianapolis AlleyCats,310,257,3669,295,380,3289,3289,310,...,0.080403,0.084492,0.094254,0.650602,0.278932,0.446043,0.469565,0.400000,0.600000,0.534043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,2019,San Diego Growlers,310,295,3187,173,215,2975,2975,310,...,0.054283,0.097270,0.104202,0.756014,0.276074,0.582707,0.626781,0.497238,0.516667,0.484029
132,2019,San Jose Spiders,263,237,3004,193,237,2768,2768,264,...,0.064248,0.087550,0.095376,0.636943,0.220280,0.514677,0.518135,0.504000,0.458824,0.388889
133,2019,Seattle Cascades,263,251,3253,220,255,2998,2998,263,...,0.067630,0.080848,0.087725,0.651235,0.185714,0.502868,0.536896,0.400000,0.433735,0.395415
134,2019,Tampa Bay Cannons,232,210,3134,222,266,2870,2870,232,...,0.070836,0.074027,0.080836,0.609155,0.237903,0.462151,0.479224,0.418440,0.459302,0.473520
135,2019,Toronto Rush,291,272,3259,231,280,2980,2980,293,...,0.070881,0.089291,0.098322,0.691525,0.276190,0.500000,0.538259,0.428571,0.575000,0.515513

In [12]:
audl_games = uap.make_team_indicators(audl_df, by_game=True)
audl_games.head()

,year,team,opponent,date,game,Assists,Hockey Assists,Throws,Throwaways,Turnovers,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2014,Chicago Wildfire,Cincinnati Revolution,2014-04-18,Chicago Wildfire_Cincinnati Revolution_2014-04-18,22,20,214,17,20,...,0.079439,0.102804,0.113402,0.760000,0.130435,0.511628,0.527778,0.428571,0.6875,0.333333
1,2014,Chicago Wildfire,Cincinnati Revolution,2014-04-26,Chicago Wildfire_Cincinnati Revolution_2014-04-26,27,22,221,23,31,...,0.104072,0.122172,0.142105,0.714286,0.607143,0.457627,0.434783,0.472222,0.7500,0.804348
2,2014,Chicago Wildfire,Cincinnati Revolution,2014-06-28,Chicago Wildfire_Cincinnati Revolution_2014-06-28,21,19,303,18,28,...,0.059406,0.069307,0.076364,0.923077,0.391304,0.420000,0.545455,0.321429,0.9000,0.756098
3,2014,Chicago Wildfire,Detroit Mechanix,2014-05-03,Chicago Wildfire_Detroit Mechanix_2014-05-03,18,15,241,30,45,...,0.124481,0.074689,0.091837,0.818182,0.473684,0.281250,0.346154,0.236842,1.0000,0.812500
4,2014,Chicago Wildfire,Detroit Mechanix,2014-06-04,Chicago Wildfire_Detroit Mechanix_2014-06-04,31,22,182,17,19,...,0.093407,0.170330,0.190184,0.944444,0.437500,0.620000,0.944444,0.437500,NaN,0.660000

In [15]:
# BROKEN :( RN
# audl_players = uap.make_player_indicators(audl_df)
# audl_players.head()

# Investigate your own team!

In [16]:
custom_pull = uap.UltiAnalyticsPuller(team_number='5686880741883904',
                                      team_name='Fakers',
                                      year=2019,
                                      output_dir='./',
                                      team_password='Fake')

In [17]:
team_df = uap.load_team_data('2019_Fakers.csv')

In [18]:
team_games = uap.make_team_indicators(team_df, by_game=True)
team_games

,year,team,opponent,date,game,Assists,Hockey Assists,Throws,Throwaways,Turnovers,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2017,Fakers,Nothings,2017-07-20,Fakers_Nothings_2017-07-20,0,0,1,0,1,...,0.0,0.000000,NaN,NaN,0.0,0.0,NaN,0.0,NaN,1.0
1,2017,Fakers,Phonies,2017-06-28,Fakers_Phonies_2017-06-28,1,1,8,0,0,...,0.0,0.125000,0.125000,NaN,1.0,1.0,NaN,1.0,NaN,1.0
2,2017,Fakers,Unreals,2017-06-28,Fakers_Unreals_2017-06-28,1,1,13,0,0,...,0.0,0.076923,0.076923,NaN,1.0,1.0,NaN,1.0,NaN,1.0

In [19]:
player_year = uap.make_player_indicators(team_df)
player_year

,year,team,player,Assists,Hockey Assists,Throws,Throwaways,Turnovers,Completions,Catches,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2017,Fakers,A,0,0,4,0,0,4,2,...,0.0,0.0,0.000000,NaN,0.666667,0.666667,NaN,0.666667,NaN,1.0
1,2017,Fakers,Anonymous,0,0,1,0,0,1,0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017,Fakers,B,0,0,4,0,0,3,3,...,0.0,0.0,0.000000,NaN,0.666667,0.666667,NaN,0.666667,NaN,1.0
3,2017,Fakers,C,0,0,3,0,1,3,3,...,0.0,0.0,0.000000,NaN,0.666667,0.666667,NaN,0.666667,NaN,1.0
4,2017,Fakers,D,0,0,2,0,0,2,3,...,0.0,0.0,0.333333,NaN,0.666667,0.666667,NaN,0.666667,NaN,1.0
5,2017,Fakers,E,1,0,5,0,0,5,4,...,0.0,0.2,0.000000,NaN,0.666667,0.666667,NaN,0.666667,NaN,1.0
6,2017,Fakers,F,0,2,0,0,0,0,3,...,NaN,NaN,0.333333,NaN,0.666667,0.666667,NaN,0.666667,NaN,1.0
7,2017,Fakers,G,0,0,1,0,0,1,2,...,0.0,0.0,0.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,1.0
8,2017,Fakers,H,1,0,2,0,0,2,1,...,0.0,0.5,0.000000,NaN,1.000000,1.000000,NaN,1.000000,NaN,1.0

In [20]:
player_game = uap.make_player_indicators(team_df, by_game=True)
player_game.head()

NOTE - the current player functions get prohibitively slow if indexed on game

,year,team,player,opponent,date,game,Assists,Hockey Assists,Throws,Throwaways,...,Throwaway Rate,Assist Rate,Goal Rate,Hold Rate,Break Rate,Scoring Efficiency,O Scoring Efficiency,D Scoring Efficiency,O Takeaway Efficiency,D Takeaway Efficiency
0,2017,Fakers,A,Nothings,2017-07-20,Fakers_Nothings_2017-07-20,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,1.0
1,2017,Fakers,A,Phonies,2017-06-28,Fakers_Phonies_2017-06-28,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0
2,2017,Fakers,A,Unreals,2017-06-28,Fakers_Unreals_2017-06-28,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0
3,2017,Fakers,Anonymous,Phonies,2017-06-28,Fakers_Phonies_2017-06-28,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017,Fakers,Anonymous,Unreals,2017-06-28,Fakers_Unreals_2017-06-28,0.0,0.0,1.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
for i in sorted(player_year.columns):
    print(i)

Assist Rate
Assists
Blocks
Break Rate
Breaks
Callahans
Callahans Thrown
Catches
Completion Rate
Completions
D Opponent Possessions Played
D Points Lost
D Points Played
D Possessions Played
D Scoring Efficiency
D Takeaway Efficiency
Drops
Games Played
Goal Rate
Goals
Hockey Assists
Hold Rate
Holds
Net Stats
O Opponent Possessions Played
O Points Lost
O Points Played
O Possessions Played
O Scoring Efficiency
O Takeaway Efficiency
Plus/Minus
Points Played
Points Won
Possessions Played
Receiving Yards
Scoring Efficiency
Stalls
Throwaway Rate
Throwaways
Throwing Yards
Throws
Turnovers
player
team
year